obj-$(CONFIG_GSV2K11) += gsv2k11_driver.o
gsv2k11_driver-objs += \
	gsv2k11_i2c.o \
	av_common.o \
	av_edid_manage.o \
	av_event_handler.o \
	av_irda_cmd.o \
	av_key_cmd.o \
	av_uart_cmd.o

gsv2k11_driver-objs += \
	kapi/kapi.o \
	kapi/kapi_debug_info.o \
	kapi/kernel_fsm.o \
	kapi/kernel_status_update.o \
	kapi/uapi_function_mapper.o

gsv2k11_driver-objs += \
	uapi/gsv2k11.o \
	uapi/hal.o \
	uapi/uapi.o
