# config declarations into driver model code

obj-$(CONFIG_AW95016)					+= aw95016/
obj-$(CONFIG_AW37004)					+= aw37004/
obj-$(CONFIG_GS2972)					+= gs2972/
obj-$(CONFIG_GMM626)					+= gmm626/
obj-$(CONFIG_STK8329)					+= stk8329/
obj-$(CONFIG_SGM7220)					+= sgm7220/
obj-$(CONFIG_GSV2K11)					+= gsv2k11/
obj-$(CONFIG_LTR381RGB)					+= ltr381rgb/
obj-$(CONFIG_HISI_TSENSOR)				+= hisi_tsensor/
obj-$(CONFIG_SH5001A)					+= sh5001a/
obj-$(CONFIG_HISI_CPUFREQ)				+= hisi_cpufreq/
obj-$(CONFIG_HISI_SVB)					+= hisi_svb/
obj-$(CONFIG_AW87559)					+= aw87559/
obj-$(CONFIG_AW89402)					+= aw89402/
obj-$(CONFIG_AW35616)					+= aw35616/